import React,{useEffect,useMemo,useState} from "react";
import {Alert,Box,Button,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,Grid,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import {getPersonnelAttendance,getPersonnelAttendanceSummary,getPersonnelEmployees,savePersonnelAttendance} from "../../api/company";

const labels={ABSENT:"Falta completa",LATE:"Tardanza",EARLY_DEPARTURE:"Salida anticipada",UNPAID_PERMISSION:"Permiso sin goce",UNPAID_SUSPENSION:"Suspensión sin goce",PRESENT:"Presente (histórico)",REMOTE:"Remoto",HOLIDAY:"Feriado",REST:"Descanso"};
const colors={PRESENT:"success",ABSENT:"error",LATE:"warning",EARLY_DEPARTURE:"warning",UNPAID_PERMISSION:"warning",UNPAID_SUSPENSION:"error",REMOTE:"info",HOLIDAY:"secondary",REST:"default"};
const incidentLabels=Object.fromEntries(Object.entries(labels).filter(([key])=>['ABSENT','LATE','EARLY_DEPARTURE','UNPAID_PERMISSION','UNPAID_SUSPENSION'].includes(key)));
const today=new Date().toISOString().slice(0,10);const monthStart=`${today.slice(0,7)}-01`;
const EMPTY={employee_id:"",attendance_date:today,attendance_status:"ABSENT",check_in:"",check_out:"",regular_hours:0,deductible_hours:0,overtime_hours:0,notes:""};

export default function PersonnelAttendancePage(){
 const [records,setRecords]=useState([]),[summary,setSummary]=useState([]),[employees,setEmployees]=useState([]),[filters,setFilters]=useState({date_from:monthStart,date_to:today}),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{setError("");const [r,s,e]=await Promise.all([getPersonnelAttendance(filters),getPersonnelAttendanceSummary(filters),getPersonnelEmployees()]);setRecords(r);setSummary(s);setEmployees(e.filter(x=>x.status==="ACTIVE"))}catch(err){setError(err?.response?.data?.message||"No se pudo cargar la asistencia.")}finally{setLoading(false)}};useEffect(()=>{load()},[filters.date_from,filters.date_to]);
 const totals=useMemo(()=>summary.reduce((a,s)=>({worked:a.worked+Number(s.worked_days||0),absent:a.absent+Number(s.absent_days||0),late:a.late+Number(s.late_days||0),overtime:a.overtime+Number(s.overtime_hours||0)}),{worked:0,absent:0,late:0,overtime:0}),[summary]);
 const save=async()=>{try{setSaving(true);setError("");await savePersonnelAttendance({...form,employee_id:Number(form.employee_id),regular_hours:Number(form.regular_hours||0),deductible_hours:Number(form.deductible_hours||0),overtime_hours:Number(form.overtime_hours||0)});setMessage("Incidencia guardada.");setOpen(false);setForm({...EMPTY,attendance_date:form.attendance_date});await load()}catch(err){setError(err?.response?.data?.message||"No se pudo guardar la incidencia.")}finally{setSaving(false)}};
 const edit=(r)=>{setForm({employee_id:r.employee_id,attendance_date:r.attendance_date,attendance_status:r.attendance_status,check_in:r.check_in?.slice(0,5)||"",check_out:r.check_out?.slice(0,5)||"",regular_hours:r.regular_hours,deductible_hours:r.deductible_hours||0,overtime_hours:r.overtime_hours,notes:r.notes||""});setOpen(true)};
 return <Box><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" spacing={2} mb={3}><Box><Typography variant="h4" fontWeight={900}>Incidencias de asistencia</Typography><Typography color="text.secondary">La jornada completa se reconoce por defecto. Registra solamente faltas, horas descontables y horas extraordinarias.</Typography></Box><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>{setForm(EMPTY);setOpen(true)}}>Registrar incidencia</Button></Stack>
 {message&&<Alert severity="success" onClose={()=>setMessage("")} sx={{mb:2}}>{message}</Alert>}{error&&<Alert severity="error" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}
 <Stack direction={{xs:"column",sm:"row"}} spacing={2} mb={2}><TextField label="Desde" type="date" size="small" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})} InputLabelProps={{shrink:true}}/><TextField label="Hasta" type="date" size="small" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})} InputLabelProps={{shrink:true}}/></Stack>
 <Stack direction={{xs:"column",md:"row"}} spacing={2} mb={3}>{[["Días trabajados",totals.worked],["Ausencias",totals.absent],["Tardanzas",totals.late],["Horas extra",totals.overtime.toFixed(2)]].map(([l,v])=><Paper key={l} sx={{p:2,flex:1,borderRadius:3}}><Typography color="text.secondary">{l}</Typography><Typography variant="h5" fontWeight={900}>{v}</Typography></Paper>)}</Stack>
 <Paper sx={{overflow:"auto",borderRadius:3}}>{loading?<Stack alignItems="center" p={5}><CircularProgress/></Stack>:<Table><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell>Colaborador</TableCell><TableCell>Incidencia</TableCell><TableCell align="right">Horas descontables</TableCell><TableCell align="right">Horas extra</TableCell><TableCell>Observación</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{records.map(r=><TableRow key={r.id}><TableCell>{r.attendance_date}</TableCell><TableCell><Typography fontWeight={800}>{r.first_name} {r.last_name}</Typography><Typography variant="caption">{r.employee_code} · {r.position}</Typography></TableCell><TableCell><Chip size="small" color={colors[r.attendance_status]} label={labels[r.attendance_status]}/></TableCell><TableCell align="right">{r.attendance_status==='ABSENT'?'Día completo':Number(r.deductible_hours||0).toFixed(2)}</TableCell><TableCell align="right">{Number(r.overtime_hours||0).toFixed(2)}</TableCell><TableCell>{r.notes||"—"}</TableCell><TableCell align="right"><Button size="small" onClick={()=>edit(r)}>Editar</Button></TableCell></TableRow>)}{!records.length&&<TableRow><TableCell colSpan={7}><Alert severity="info" sx={{position:"static"}}>No hay incidencias en el período seleccionado. La nómina se pagará completa por defecto.</Alert></TableCell></TableRow>}</TableBody></Table>}</Paper>
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={900}>Registrar incidencia</DialogTitle><DialogContent dividers><Grid container spacing={2}><Grid item xs={12}><Alert severity="info" sx={{position:"static"}}>No necesitas registrar días normales. La planilla paga el período completo y resta únicamente estas incidencias.</Alert></Grid><Grid item xs={12}><TextField select label="Colaborador" value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} fullWidth required>{employees.map(e=><MenuItem key={e.id} value={e.id}>{e.first_name} {e.last_name} — {e.position}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField label="Fecha" type="date" value={form.attendance_date} onChange={e=>setForm({...form,attendance_date:e.target.value})} InputLabelProps={{shrink:true}} fullWidth required/></Grid><Grid item xs={12} sm={6}><TextField select label="Tipo de incidencia" value={form.attendance_status} onChange={e=>setForm({...form,attendance_status:e.target.value,deductible_hours:e.target.value==='ABSENT'?0:form.deductible_hours})} fullWidth>{Object.entries(incidentLabels).map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField></Grid>{form.attendance_status!=='ABSENT'&&<Grid item xs={12} sm={6}><TextField label="Horas a descontar" type="number" value={form.deductible_hours} onChange={e=>setForm({...form,deductible_hours:e.target.value})} inputProps={{min:0.25,max:24,step:"0.25"}} required fullWidth/></Grid>}<Grid item xs={12} sm={6}><TextField label="Horas extra (opcional)" type="number" value={form.overtime_hours} onChange={e=>setForm({...form,overtime_hours:e.target.value})} inputProps={{min:0,max:24,step:"0.25"}} fullWidth/></Grid><Grid item xs={12}><TextField label="Observación / soporte" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} multiline minRows={2} fullWidth/></Grid></Grid></DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setOpen(false)} disabled={saving}>Cancelar</Button><Button variant="contained" onClick={save} disabled={saving||!form.employee_id||!form.attendance_date||(form.attendance_status!=='ABSENT'&&Number(form.deductible_hours)<=0)}>{saving?"Guardando...":"Guardar incidencia"}</Button></DialogActions></Dialog>
 </Box>;
}
