import React,{useEffect,useMemo,useState} from "react";
import {Alert,Box,Button,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,Grid,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import {createPersonnelLeaveRequest,getPersonnelEmployees,getPersonnelLeaveBalances,getPersonnelLeaveRequests,reviewPersonnelLeaveRequest} from "../../api/company";

const labels={VACATION:"Vacaciones",PERMISSION:"Permiso",SICK_LEAVE:"Subsidio / enfermedad"};
const statusLabels={PENDING:"Pendiente",APPROVED:"Aprobada",REJECTED:"Rechazada",CANCELLED:"Cancelada"};
const statusColors={PENDING:"warning",APPROVED:"success",REJECTED:"error",CANCELLED:"default"};
const EMPTY={employee_id:"",leave_type:"VACATION",start_date:"",end_date:"",paid:true,reason:""};

export default function PersonnelLeavePage(){
 const [requests,setRequests]=useState([]),[balances,setBalances]=useState([]),[employees,setEmployees]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(EMPTY),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{setError("");const [r,b,e]=await Promise.all([getPersonnelLeaveRequests(),getPersonnelLeaveBalances(),getPersonnelEmployees()]);setRequests(r);setBalances(b);setEmployees(e.filter(x=>x.status==="ACTIVE"))}catch(err){setError(err?.response?.data?.message||"No se pudo cargar vacaciones y permisos.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const pending=useMemo(()=>requests.filter(r=>r.status==="PENDING").length,[requests]);
 const save=async()=>{try{setSaving(true);setError("");await createPersonnelLeaveRequest({...form,employee_id:Number(form.employee_id)});setMessage("Solicitud registrada.");setOpen(false);setForm(EMPTY);await load()}catch(err){setError(err?.response?.data?.message||"No se pudo registrar la solicitud.")}finally{setSaving(false)}};
 const review=async(id,status)=>{try{setError("");await reviewPersonnelLeaveRequest(id,status);setMessage(status==="APPROVED"?"Solicitud aprobada.":"Solicitud rechazada.");await load()}catch(err){setError(err?.response?.data?.message||"No se pudo revisar la solicitud.")}};
 return <Box><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" spacing={2} mb={3}><Box><Typography variant="h4" fontWeight={900}>Vacaciones y permisos</Typography><Typography color="text.secondary">Saldos y control de ausencias del personal.</Typography></Box><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setOpen(true)}>Nueva solicitud</Button></Stack>
 {message&&<Alert severity="success" onClose={()=>setMessage("")} sx={{mb:2}}>{message}</Alert>}{error&&<Alert severity="error" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}
 <Stack direction={{xs:"column",md:"row"}} spacing={2} mb={3}>{[["Solicitudes pendientes",pending],["Colaboradores con saldo",balances.length],["Días disponibles",balances.reduce((s,b)=>s+Number(b.available_days||0),0).toFixed(2)]].map(([l,v])=><Paper key={l} sx={{p:2,flex:1,borderRadius:3}}><Typography color="text.secondary">{l}</Typography><Typography variant="h5" fontWeight={900}>{v}</Typography></Paper>)}</Stack>
 <Typography variant="h6" fontWeight={900} mb={1}>Saldos de vacaciones</Typography><Paper sx={{overflow:"auto",borderRadius:3,mb:3}}>{loading?<Stack alignItems="center" p={4}><CircularProgress/></Stack>:<Table size="small"><TableHead><TableRow><TableCell>Colaborador</TableCell><TableCell>Fecha de ingreso</TableCell><TableCell align="right">Acumulado</TableCell><TableCell align="right">Utilizado</TableCell><TableCell align="right">Disponible</TableCell></TableRow></TableHead><TableBody>{balances.map(b=><TableRow key={b.id}><TableCell><Typography fontWeight={800}>{b.first_name} {b.last_name}</Typography><Typography variant="caption">{b.employee_code}</Typography></TableCell><TableCell>{b.hire_date}</TableCell><TableCell align="right">{b.accrued_days}</TableCell><TableCell align="right">{b.used_days}</TableCell><TableCell align="right"><Typography fontWeight={900} color="success.main">{b.available_days}</Typography></TableCell></TableRow>)}</TableBody></Table>}</Paper>
 <Typography variant="h6" fontWeight={900} mb={1}>Solicitudes</Typography><Paper sx={{overflow:"auto",borderRadius:3}}><Table><TableHead><TableRow><TableCell>Colaborador</TableCell><TableCell>Tipo</TableCell><TableCell>Período</TableCell><TableCell align="right">Días</TableCell><TableCell>Pago</TableCell><TableCell>Estado</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{requests.map(r=><TableRow key={r.id}><TableCell><Typography fontWeight={800}>{r.first_name} {r.last_name}</Typography><Typography variant="caption">{r.reason||"Sin observación"}</Typography></TableCell><TableCell>{labels[r.leave_type]}</TableCell><TableCell>{r.start_date} al {r.end_date}</TableCell><TableCell align="right">{r.requested_days}</TableCell><TableCell>{r.paid?"Con goce":"Sin goce"}</TableCell><TableCell><Chip size="small" color={statusColors[r.status]} label={statusLabels[r.status]}/></TableCell><TableCell align="right">{r.status==="PENDING"&&<><Button size="small" color="success" onClick={()=>review(r.id,"APPROVED")}>Aprobar</Button><Button size="small" color="error" onClick={()=>review(r.id,"REJECTED")}>Rechazar</Button></>}</TableCell></TableRow>)}{!requests.length&&<TableRow><TableCell colSpan={7}><Alert severity="info" sx={{position:"static"}}>Todavía no hay solicitudes.</Alert></TableCell></TableRow>}</TableBody></Table></Paper>
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={900}>Nueva solicitud</DialogTitle><DialogContent dividers><Grid container spacing={2}><Grid item xs={12}><TextField select label="Colaborador" value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} fullWidth required>{employees.map(e=><MenuItem key={e.id} value={e.id}>{e.first_name} {e.last_name} — {e.position}</MenuItem>)}</TextField></Grid><Grid item xs={12}><TextField select label="Tipo" value={form.leave_type} onChange={e=>setForm({...form,leave_type:e.target.value})} fullWidth>{Object.entries(labels).map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField label="Desde" type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})} InputLabelProps={{shrink:true}} fullWidth required/></Grid><Grid item xs={12} sm={6}><TextField label="Hasta" type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})} InputLabelProps={{shrink:true}} fullWidth required/></Grid><Grid item xs={12}><TextField select label="Remuneración" value={form.paid?"1":"0"} onChange={e=>setForm({...form,paid:e.target.value==="1"})} fullWidth><MenuItem value="1">Con goce de salario</MenuItem><MenuItem value="0">Sin goce de salario</MenuItem></TextField></Grid><Grid item xs={12}><TextField label="Motivo / observaciones" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} multiline minRows={3} fullWidth/></Grid></Grid></DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setOpen(false)} disabled={saving}>Cancelar</Button><Button variant="contained" onClick={save} disabled={saving||!form.employee_id||!form.start_date||!form.end_date}>{saving?"Guardando...":"Registrar solicitud"}</Button></DialogActions></Dialog>
 </Box>;
}
