import React,{useEffect,useState} from "react";
import {Alert,Box,Button,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,Grid,Paper,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import {approvePersonnelBenefitRun,createPersonnelThirteenthMonth,getPersonnelBenefitRun,getPersonnelBenefitRuns} from "../../api/company";

const currentYear=new Date().getFullYear();const money=v=>new Intl.NumberFormat("es-NI",{style:"currency",currency:"NIO"}).format(Number(v||0));
export default function PersonnelBenefitsPage(){
 const [runs,setRuns]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState({year:currentYear,payment_date:`${currentYear}-12-10`}),[saving,setSaving]=useState(false),[detail,setDetail]=useState(null),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{setError("");setRuns(await getPersonnelBenefitRuns())}catch(e){setError(e?.response?.data?.message||"No se pudieron cargar las prestaciones.")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const create=async()=>{try{setSaving(true);setError("");const r=await createPersonnelThirteenthMonth({year:Number(form.year),payment_date:form.payment_date});setMessage(`Aguinaldo calculado para ${r.employees} colaborador(es).`);setOpen(false);await load()}catch(e){setError(e?.response?.data?.message||"No se pudo calcular el aguinaldo.")}finally{setSaving(false)}};
 const view=async(id)=>{try{setDetail(await getPersonnelBenefitRun(id))}catch(e){setError(e?.response?.data?.message||"No se pudo cargar el detalle.")}};
 const approve=async()=>{try{setSaving(true);await approvePersonnelBenefitRun(detail.id);setMessage("Aguinaldo aprobado y cerrado.");setDetail(null);await load()}catch(e){setError(e?.response?.data?.message||"No se pudo aprobar el aguinaldo.")}finally{setSaving(false)}};
 return <Box><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" spacing={2} mb={3}><Box><Typography variant="h4" fontWeight={900}>Prestaciones laborales</Typography><Typography color="text.secondary">Cálculo y control del décimo tercer mes.</Typography></Box><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setOpen(true)}>Calcular aguinaldo</Button></Stack>
 <Alert severity="info" sx={{mb:2,position:"static"}}>El aguinaldo se calcula sin INSS ni IR. Para salarios variables debe verificarse manualmente el salario aplicable antes de aprobar.</Alert>{message&&<Alert severity="success" onClose={()=>setMessage("")} sx={{mb:2}}>{message}</Alert>}{error&&<Alert severity="error" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}
 <Paper sx={{overflow:"auto",borderRadius:3}}>{loading?<Stack alignItems="center" p={5}><CircularProgress/></Stack>:<Table><TableHead><TableRow><TableCell>Prestación</TableCell><TableCell>Período acumulado</TableCell><TableCell>Fecha de pago</TableCell><TableCell align="right">Total</TableCell><TableCell>Estado</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{runs.map(r=><TableRow key={r.id}><TableCell><Typography fontWeight={800}>Aguinaldo {r.benefit_year}</Typography></TableCell><TableCell>{r.period_start} al {r.period_end}</TableCell><TableCell>{r.payment_date}</TableCell><TableCell align="right"><Typography fontWeight={900}>{money(r.total_amount)}</Typography></TableCell><TableCell><Chip size="small" color={r.status==="APPROVED"?"success":"warning"} label={r.status==="APPROVED"?"Aprobado":"Borrador"}/></TableCell><TableCell align="right"><Button size="small" onClick={()=>view(r.id)}>Revisar</Button></TableCell></TableRow>)}{!runs.length&&<TableRow><TableCell colSpan={6}><Alert severity="info" sx={{position:"static"}}>Todavía no hay prestaciones calculadas.</Alert></TableCell></TableRow>}</TableBody></Table>}</Paper>
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="xs"><DialogTitle fontWeight={900}>Calcular aguinaldo</DialogTitle><DialogContent dividers><Stack spacing={2}><TextField label="Año" type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value,payment_date:`${e.target.value}-12-10`})} inputProps={{min:2020,max:2100}} fullWidth/><TextField label="Fecha de pago" type="date" value={form.payment_date} onChange={e=>setForm({...form,payment_date:e.target.value})} InputLabelProps={{shrink:true}} fullWidth/><Typography variant="body2" color="text.secondary">Período: 1 de diciembre del año anterior al 30 de noviembre del año seleccionado.</Typography></Stack></DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setOpen(false)} disabled={saving}>Cancelar</Button><Button variant="contained" onClick={create} disabled={saving||!form.year||!form.payment_date}>{saving?"Calculando...":"Generar borrador"}</Button></DialogActions></Dialog>
 <Dialog open={Boolean(detail)} onClose={()=>!saving&&setDetail(null)} fullWidth maxWidth="md"><DialogTitle fontWeight={900}>Aguinaldo {detail?.benefit_year}</DialogTitle><DialogContent dividers>{detail&&<><Stack direction="row" justifyContent="space-between" mb={2}><Typography>Total</Typography><Typography variant="h5" fontWeight={900}>{money(detail.total_amount)}</Typography></Stack><Table size="small"><TableHead><TableRow><TableCell>Colaborador</TableCell><TableCell>Período elegible</TableCell><TableCell align="right">Días</TableCell><TableCell align="right">Salario base</TableCell><TableCell align="right">Aguinaldo</TableCell></TableRow></TableHead><TableBody>{detail.items?.map(i=><TableRow key={i.id}><TableCell>{i.employee_name}<Typography variant="caption" display="block">{i.employee_code}</Typography></TableCell><TableCell>{i.eligible_from} al {i.eligible_to}</TableCell><TableCell align="right">{i.eligible_days}</TableCell><TableCell align="right">{money(i.monthly_salary)}</TableCell><TableCell align="right"><b>{money(i.amount)}</b></TableCell></TableRow>)}</TableBody></Table></>}</DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setDetail(null)}>Cerrar</Button>{detail?.status==="DRAFT"&&<Button variant="contained" color="success" onClick={approve} disabled={saving||!detail?.items?.length}>{saving?"Aprobando...":"Aprobar y cerrar"}</Button>}</DialogActions></Dialog>
 </Box>;
}
