import React,{useEffect,useMemo,useState} from "react";
import {Alert,Box,Button,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,Grid,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from "@mui/material";
import UploadFileIcon from "@mui/icons-material/UploadFile";
import {archivePersonnelDocument,createPersonnelDocument,getPersonnelDocuments,getPersonnelEmployees} from "../../api/company";

const types={CONTRACT:"Contrato",IDENTITY:"Identificación",INSS:"INSS",MEDICAL:"Documento médico",CERTIFICATE:"Constancia",PAYROLL_SUPPORT:"Soporte de planilla",OTHER:"Otro"};
const expiryLabels={NO_EXPIRY:"Sin vencimiento",VALID:"Vigente",EXPIRING:"Próximo a vencer",EXPIRED:"Vencido"};
const expiryColors={NO_EXPIRY:"default",VALID:"success",EXPIRING:"warning",EXPIRED:"error"};
const EMPTY={employee_id:"",document_type:"CONTRACT",title:"",issued_at:"",expires_at:"",notes:"",file:null};

export default function PersonnelDocumentsPage(){
 const [documents,setDocuments]=useState([]),[employees,setEmployees]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(EMPTY),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{setError("");const [docs,emps]=await Promise.all([getPersonnelDocuments(),getPersonnelEmployees()]);setDocuments(docs);setEmployees(emps)}catch(e){setError(e?.response?.data?.message||"No se pudieron cargar los documentos.")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const stats=useMemo(()=>({active:documents.filter(d=>d.status==="ACTIVE").length,expiring:documents.filter(d=>d.status==="ACTIVE"&&d.expiry_status==="EXPIRING").length,expired:documents.filter(d=>d.status==="ACTIVE"&&d.expiry_status==="EXPIRED").length}),[documents]);
 const save=async()=>{try{setSaving(true);setError("");const data=new FormData();Object.entries(form).forEach(([k,v])=>{if(k==="file"){if(v)data.append("personnel_document",v)}else data.append(k,v??"")});await createPersonnelDocument(data);setMessage("Documento cargado correctamente.");setOpen(false);setForm(EMPTY);await load()}catch(e){setError(e?.response?.data?.message||"No se pudo cargar el documento.")}finally{setSaving(false)}};
 const archive=async(id)=>{try{await archivePersonnelDocument(id);setMessage("Documento archivado.");await load()}catch(e){setError(e?.response?.data?.message||"No se pudo archivar el documento.")}};
 return <Box><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" spacing={2} mb={3}><Box><Typography variant="h4" fontWeight={900}>Documentos laborales</Typography><Typography color="text.secondary">Archivo y control de vigencia de documentos del personal.</Typography></Box><Button variant="contained" startIcon={<UploadFileIcon/>} onClick={()=>setOpen(true)}>Cargar documento</Button></Stack>
 {message&&<Alert severity="success" onClose={()=>setMessage("")} sx={{mb:2}}>{message}</Alert>}{error&&<Alert severity="error" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}
 <Stack direction={{xs:"column",md:"row"}} spacing={2} mb={3}>{[["Documentos activos",stats.active],["Próximos a vencer",stats.expiring],["Vencidos",stats.expired]].map(([l,v])=><Paper key={l} sx={{p:2,flex:1,borderRadius:3}}><Typography color="text.secondary">{l}</Typography><Typography variant="h5" fontWeight={900}>{v}</Typography></Paper>)}</Stack>
 <Paper sx={{overflow:"auto",borderRadius:3}}>{loading?<Stack alignItems="center" p={5}><CircularProgress/></Stack>:<Table><TableHead><TableRow><TableCell>Documento</TableCell><TableCell>Colaborador</TableCell><TableCell>Tipo</TableCell><TableCell>Emisión</TableCell><TableCell>Vencimiento</TableCell><TableCell>Vigencia</TableCell><TableCell>Estado</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{documents.map(d=><TableRow key={d.id}><TableCell><Typography fontWeight={800}>{d.title}</Typography><Typography variant="caption">{d.original_name}</Typography></TableCell><TableCell>{d.first_name} {d.last_name}<Typography variant="caption" display="block">{d.employee_code}</Typography></TableCell><TableCell>{types[d.document_type]}</TableCell><TableCell>{d.issued_at||"—"}</TableCell><TableCell>{d.expires_at||"—"}</TableCell><TableCell><Chip size="small" color={expiryColors[d.expiry_status]} label={expiryLabels[d.expiry_status]}/></TableCell><TableCell>{d.status==="ACTIVE"?"Activo":"Archivado"}</TableCell><TableCell align="right"><Button size="small" component="a" href={d.file_url} target="_blank" rel="noreferrer">Abrir</Button>{d.status==="ACTIVE"&&<Button size="small" color="warning" onClick={()=>archive(d.id)}>Archivar</Button>}</TableCell></TableRow>)}{!documents.length&&<TableRow><TableCell colSpan={8}><Alert severity="info" sx={{position:"static"}}>Todavía no hay documentos laborales.</Alert></TableCell></TableRow>}</TableBody></Table>}</Paper>
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={900}>Cargar documento laboral</DialogTitle><DialogContent dividers><Grid container spacing={2}><Grid item xs={12}><TextField select label="Colaborador" value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} fullWidth required>{employees.map(e=><MenuItem key={e.id} value={e.id}>{e.first_name} {e.last_name} — {e.position}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField select label="Tipo" value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})} fullWidth>{Object.entries(types).map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField label="Título" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required fullWidth/></Grid><Grid item xs={12} sm={6}><TextField label="Fecha de emisión" type="date" value={form.issued_at} onChange={e=>setForm({...form,issued_at:e.target.value})} InputLabelProps={{shrink:true}} fullWidth/></Grid><Grid item xs={12} sm={6}><TextField label="Fecha de vencimiento" type="date" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})} InputLabelProps={{shrink:true}} fullWidth/></Grid><Grid item xs={12}><Button component="label" variant="outlined" startIcon={<UploadFileIcon/>} fullWidth>{form.file?form.file.name:"Seleccionar archivo PDF, Word o imagen"}<input hidden type="file" accept=".pdf,.doc,.docx,image/jpeg,image/png,image/webp" onChange={e=>setForm({...form,file:e.target.files?.[0]||null})}/></Button><Typography variant="caption" color="text.secondary">Tamaño máximo: 8 MB.</Typography></Grid><Grid item xs={12}><TextField label="Notas" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} multiline minRows={2} fullWidth/></Grid></Grid></DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setOpen(false)} disabled={saving}>Cancelar</Button><Button variant="contained" onClick={save} disabled={saving||!form.employee_id||!form.title.trim()||!form.file}>{saving?"Subiendo...":"Guardar documento"}</Button></DialogActions></Dialog>
 </Box>;
}
